/*  Jobby's main theme colors!  *

/* Generated by Brackets Swatcher */
export const violet = '#434fa8'; // royalblue
export const blue = '#3F96D4'; //havelockblue
export const red = '#DE5950;'; //roman
export const lightGray = '#F1F5F9'; //catskillwhite
export const blueGreyLigthen5 = '#eceff1'; // from material googles's standarts


